### ISSUE TITLE
If a shard can't be loaded, should we start the other shards?

### ISSUE THREAD

**Issue by mcpherrinm** [FiloSottile/sunlight#27]
I'm not sure what the right answer here is, but while adding willow-2024h2c, the new config wasn't valid (wrong inception date, per #26), and so the existing shards also stopped running when Sunlight restarted with the new config, which isn't great. I'm not sure what the right course of action is, but I thought I'd note it as a pain point.

**Comment by FiloSottile** [comment]
I've been thinking about this (and was bitten by it as well) and I think ultimately it's better not to run, making it very clear there is a problem and hopefully what it is, than to run degraded, which might be easy to miss tailing logs. Also, a restart might fix the issue if it is a transient failure, and I wouldn't like to get into the per-shard scheduling and backoff game. Finally, right now health is binary, which is easy to alert on and to wire into systemd or whatever.

Rollbacks of configs should more or less always work, so that's always the option to restore the other shards.

**Comment by mcpherrinm** [comment]
I think I'm in agreement.  As a different way of thinking about it:  I can always just run more Sunlight instances if I want them to be independent. And since I'm now producing the configurations for my own logs with Terraform, I have a fair amount of confidence the rest of the configs are correct and can always further invest in that path.  Happy to close this.
